### PR TITLE
fix kernel exceptions when turn on/off streaming on JP 5.1.2.

### PR DESCRIPTION
**Pull request by mengyui**
Fix kernel exceptions which thrown when turn on/off streamings.

### CODE REVIEW

**Comment by Nir-Az** [comment]
@mengyui  is this related to 5.1.2 version only?
Can you elaborate on the fix and add the kernel exception?

**Comment by mengyui** [comment]
Not sure it's JP 5.1.2 only. I will validate it on JP 6 next step.

the issue is passing a wrong channel_id to vi_channel_[open|close]_ex in this patch, comparing with the other code calling vi_channel_[open|close]_ex function.

**Comment by Nir-Az** [comment]
@dmipx please review

**Comment by mengyui** [comment]
Sorry. I got randomly crash on Orin AGX+JP5.1.2+https://github.com/mengyui/realsense_mipi_platform_driver/blob/fangzhu-fg96-dev/hardware/realsense/tegra234-p3737-camera-d4xx-fg96-8ch-single.dtsi
"Unable to handle kernel NULL pointer dereference at virtual address 0000000000000020"
I will try to fix the new crash issue. Should I close this PR for now? and create a new one in the future.

**Comment by Nir-Az** [comment]
> Sorry. I got randomly crash on Orin AGX+JP5.1.2+https://github.com/mengyui/realsense_mipi_platform_driver/blob/fangzhu-fg96-dev/hardware/realsense/tegra234-p3737-camera-d4xx-fg96-8ch-single.dtsi "Unable to handle kernel NULL pointer dereference at virtual address 0000000000000020" I will try to fix the new crash issue. Should I close this PR for now? and create a new one in the future.

Your choice, might be better :)

**Comment by mengyui** [comment]
Thanks. trying to find the new fix.

**Pull request closed without merging**
